// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NativeRtbContainer.proto

package com.google.openbidder.containers;

public final class NativeRtbContainer {
  private NativeRtbContainer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestContainerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.google.openbidder.containers.RequestContainer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional bytes request = 2;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional bytes request = 2;</code>
     */
    com.google.protobuf.ByteString getRequest();

    /**
     * <code>optional int32 campaignId = 3;</code>
     */
    boolean hasCampaignId();
    /**
     * <code>optional int32 campaignId = 3;</code>
     */
    int getCampaignId();

    /**
     * <code>optional int32 creativeId = 4;</code>
     */
    boolean hasCreativeId();
    /**
     * <code>optional int32 creativeId = 4;</code>
     */
    int getCreativeId();

    /**
     * <code>optional string buyerCreativeId = 5;</code>
     */
    boolean hasBuyerCreativeId();
    /**
     * <code>optional string buyerCreativeId = 5;</code>
     */
    java.lang.String getBuyerCreativeId();
    /**
     * <code>optional string buyerCreativeId = 5;</code>
     */
    com.google.protobuf.ByteString
        getBuyerCreativeIdBytes();

    /**
     * <code>optional int32 impressionId = 6;</code>
     */
    boolean hasImpressionId();
    /**
     * <code>optional int32 impressionId = 6;</code>
     */
    int getImpressionId();

    /**
     * <code>optional int32 bidId = 7;</code>
     */
    boolean hasBidId();
    /**
     * <code>optional int32 bidId = 7;</code>
     */
    int getBidId();

    /**
     * <code>optional double price = 8;</code>
     */
    boolean hasPrice();
    /**
     * <code>optional double price = 8;</code>
     */
    double getPrice();

    /**
     * <code>optional string region = 9;</code>
     */
    boolean hasRegion();
    /**
     * <code>optional string region = 9;</code>
     */
    java.lang.String getRegion();
    /**
     * <code>optional string region = 9;</code>
     */
    com.google.protobuf.ByteString
        getRegionBytes();
  }
  /**
   * Protobuf type {@code com.google.openbidder.containers.RequestContainer}
   */
  public static final class RequestContainer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.google.openbidder.containers.RequestContainer)
      RequestContainerOrBuilder {
    // Use RequestContainer.newBuilder() to construct.
    private RequestContainer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestContainer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestContainer defaultInstance;
    public static RequestContainer getDefaultInstance() {
      return defaultInstance;
    }

    public RequestContainer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestContainer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              request_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              campaignId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              creativeId_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              buyerCreativeId_ = bs;
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              impressionId_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              bidId_ = input.readInt32();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              price_ = input.readDouble();
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              region_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.openbidder.containers.NativeRtbContainer.internal_static_com_google_openbidder_containers_RequestContainer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.openbidder.containers.NativeRtbContainer.internal_static_com_google_openbidder_containers_RequestContainer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.openbidder.containers.NativeRtbContainer.RequestContainer.class, com.google.openbidder.containers.NativeRtbContainer.RequestContainer.Builder.class);
    }

    public static com.google.protobuf.Parser<RequestContainer> PARSER =
        new com.google.protobuf.AbstractParser<RequestContainer>() {
      public RequestContainer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestContainer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RequestContainer> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString request_;
    /**
     * <code>optional bytes request = 2;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes request = 2;</code>
     */
    public com.google.protobuf.ByteString getRequest() {
      return request_;
    }

    public static final int CAMPAIGNID_FIELD_NUMBER = 3;
    private int campaignId_;
    /**
     * <code>optional int32 campaignId = 3;</code>
     */
    public boolean hasCampaignId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 campaignId = 3;</code>
     */
    public int getCampaignId() {
      return campaignId_;
    }

    public static final int CREATIVEID_FIELD_NUMBER = 4;
    private int creativeId_;
    /**
     * <code>optional int32 creativeId = 4;</code>
     */
    public boolean hasCreativeId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 creativeId = 4;</code>
     */
    public int getCreativeId() {
      return creativeId_;
    }

    public static final int BUYERCREATIVEID_FIELD_NUMBER = 5;
    private java.lang.Object buyerCreativeId_;
    /**
     * <code>optional string buyerCreativeId = 5;</code>
     */
    public boolean hasBuyerCreativeId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string buyerCreativeId = 5;</code>
     */
    public java.lang.String getBuyerCreativeId() {
      java.lang.Object ref = buyerCreativeId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          buyerCreativeId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string buyerCreativeId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBuyerCreativeIdBytes() {
      java.lang.Object ref = buyerCreativeId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        buyerCreativeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMPRESSIONID_FIELD_NUMBER = 6;
    private int impressionId_;
    /**
     * <code>optional int32 impressionId = 6;</code>
     */
    public boolean hasImpressionId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 impressionId = 6;</code>
     */
    public int getImpressionId() {
      return impressionId_;
    }

    public static final int BIDID_FIELD_NUMBER = 7;
    private int bidId_;
    /**
     * <code>optional int32 bidId = 7;</code>
     */
    public boolean hasBidId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 bidId = 7;</code>
     */
    public int getBidId() {
      return bidId_;
    }

    public static final int PRICE_FIELD_NUMBER = 8;
    private double price_;
    /**
     * <code>optional double price = 8;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional double price = 8;</code>
     */
    public double getPrice() {
      return price_;
    }

    public static final int REGION_FIELD_NUMBER = 9;
    private java.lang.Object region_;
    /**
     * <code>optional string region = 9;</code>
     */
    public boolean hasRegion() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string region = 9;</code>
     */
    public java.lang.String getRegion() {
      java.lang.Object ref = region_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          region_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string region = 9;</code>
     */
    public com.google.protobuf.ByteString
        getRegionBytes() {
      java.lang.Object ref = region_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        region_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = "";
      request_ = com.google.protobuf.ByteString.EMPTY;
      campaignId_ = 0;
      creativeId_ = 0;
      buyerCreativeId_ = "";
      impressionId_ = 0;
      bidId_ = 0;
      price_ = 0D;
      region_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, request_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, campaignId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, creativeId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getBuyerCreativeIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, impressionId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, bidId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeDouble(8, price_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getRegionBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, request_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, campaignId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, creativeId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getBuyerCreativeIdBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, impressionId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, bidId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, price_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getRegionBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.google.openbidder.containers.NativeRtbContainer.RequestContainer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.openbidder.containers.NativeRtbContainer.RequestContainer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.openbidder.containers.NativeRtbContainer.RequestContainer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.openbidder.containers.NativeRtbContainer.RequestContainer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.openbidder.containers.NativeRtbContainer.RequestContainer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.openbidder.containers.NativeRtbContainer.RequestContainer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.google.openbidder.containers.NativeRtbContainer.RequestContainer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.google.openbidder.containers.NativeRtbContainer.RequestContainer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.google.openbidder.containers.NativeRtbContainer.RequestContainer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.google.openbidder.containers.NativeRtbContainer.RequestContainer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.google.openbidder.containers.NativeRtbContainer.RequestContainer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.google.openbidder.containers.RequestContainer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.google.openbidder.containers.RequestContainer)
        com.google.openbidder.containers.NativeRtbContainer.RequestContainerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.openbidder.containers.NativeRtbContainer.internal_static_com_google_openbidder_containers_RequestContainer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.openbidder.containers.NativeRtbContainer.internal_static_com_google_openbidder_containers_RequestContainer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.openbidder.containers.NativeRtbContainer.RequestContainer.class, com.google.openbidder.containers.NativeRtbContainer.RequestContainer.Builder.class);
      }

      // Construct using com.google.openbidder.containers.NativeRtbContainer.RequestContainer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        request_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        campaignId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        creativeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        buyerCreativeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        impressionId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        bidId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        price_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        region_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.openbidder.containers.NativeRtbContainer.internal_static_com_google_openbidder_containers_RequestContainer_descriptor;
      }

      public com.google.openbidder.containers.NativeRtbContainer.RequestContainer getDefaultInstanceForType() {
        return com.google.openbidder.containers.NativeRtbContainer.RequestContainer.getDefaultInstance();
      }

      public com.google.openbidder.containers.NativeRtbContainer.RequestContainer build() {
        com.google.openbidder.containers.NativeRtbContainer.RequestContainer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.openbidder.containers.NativeRtbContainer.RequestContainer buildPartial() {
        com.google.openbidder.containers.NativeRtbContainer.RequestContainer result = new com.google.openbidder.containers.NativeRtbContainer.RequestContainer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.request_ = request_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.campaignId_ = campaignId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.creativeId_ = creativeId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.buyerCreativeId_ = buyerCreativeId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.impressionId_ = impressionId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.bidId_ = bidId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.region_ = region_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.openbidder.containers.NativeRtbContainer.RequestContainer) {
          return mergeFrom((com.google.openbidder.containers.NativeRtbContainer.RequestContainer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.openbidder.containers.NativeRtbContainer.RequestContainer other) {
        if (other == com.google.openbidder.containers.NativeRtbContainer.RequestContainer.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasRequest()) {
          setRequest(other.getRequest());
        }
        if (other.hasCampaignId()) {
          setCampaignId(other.getCampaignId());
        }
        if (other.hasCreativeId()) {
          setCreativeId(other.getCreativeId());
        }
        if (other.hasBuyerCreativeId()) {
          bitField0_ |= 0x00000010;
          buyerCreativeId_ = other.buyerCreativeId_;
          onChanged();
        }
        if (other.hasImpressionId()) {
          setImpressionId(other.getImpressionId());
        }
        if (other.hasBidId()) {
          setBidId(other.getBidId());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasRegion()) {
          bitField0_ |= 0x00000100;
          region_ = other.region_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.openbidder.containers.NativeRtbContainer.RequestContainer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.openbidder.containers.NativeRtbContainer.RequestContainer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString request_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes request = 2;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes request = 2;</code>
       */
      public com.google.protobuf.ByteString getRequest() {
        return request_;
      }
      /**
       * <code>optional bytes request = 2;</code>
       */
      public Builder setRequest(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        request_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes request = 2;</code>
       */
      public Builder clearRequest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        request_ = getDefaultInstance().getRequest();
        onChanged();
        return this;
      }

      private int campaignId_ ;
      /**
       * <code>optional int32 campaignId = 3;</code>
       */
      public boolean hasCampaignId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 campaignId = 3;</code>
       */
      public int getCampaignId() {
        return campaignId_;
      }
      /**
       * <code>optional int32 campaignId = 3;</code>
       */
      public Builder setCampaignId(int value) {
        bitField0_ |= 0x00000004;
        campaignId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 campaignId = 3;</code>
       */
      public Builder clearCampaignId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        campaignId_ = 0;
        onChanged();
        return this;
      }

      private int creativeId_ ;
      /**
       * <code>optional int32 creativeId = 4;</code>
       */
      public boolean hasCreativeId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 creativeId = 4;</code>
       */
      public int getCreativeId() {
        return creativeId_;
      }
      /**
       * <code>optional int32 creativeId = 4;</code>
       */
      public Builder setCreativeId(int value) {
        bitField0_ |= 0x00000008;
        creativeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 creativeId = 4;</code>
       */
      public Builder clearCreativeId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        creativeId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object buyerCreativeId_ = "";
      /**
       * <code>optional string buyerCreativeId = 5;</code>
       */
      public boolean hasBuyerCreativeId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string buyerCreativeId = 5;</code>
       */
      public java.lang.String getBuyerCreativeId() {
        java.lang.Object ref = buyerCreativeId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            buyerCreativeId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string buyerCreativeId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getBuyerCreativeIdBytes() {
        java.lang.Object ref = buyerCreativeId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          buyerCreativeId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string buyerCreativeId = 5;</code>
       */
      public Builder setBuyerCreativeId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        buyerCreativeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string buyerCreativeId = 5;</code>
       */
      public Builder clearBuyerCreativeId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        buyerCreativeId_ = getDefaultInstance().getBuyerCreativeId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string buyerCreativeId = 5;</code>
       */
      public Builder setBuyerCreativeIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        buyerCreativeId_ = value;
        onChanged();
        return this;
      }

      private int impressionId_ ;
      /**
       * <code>optional int32 impressionId = 6;</code>
       */
      public boolean hasImpressionId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 impressionId = 6;</code>
       */
      public int getImpressionId() {
        return impressionId_;
      }
      /**
       * <code>optional int32 impressionId = 6;</code>
       */
      public Builder setImpressionId(int value) {
        bitField0_ |= 0x00000020;
        impressionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 impressionId = 6;</code>
       */
      public Builder clearImpressionId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        impressionId_ = 0;
        onChanged();
        return this;
      }

      private int bidId_ ;
      /**
       * <code>optional int32 bidId = 7;</code>
       */
      public boolean hasBidId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 bidId = 7;</code>
       */
      public int getBidId() {
        return bidId_;
      }
      /**
       * <code>optional int32 bidId = 7;</code>
       */
      public Builder setBidId(int value) {
        bitField0_ |= 0x00000040;
        bidId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 bidId = 7;</code>
       */
      public Builder clearBidId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        bidId_ = 0;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>optional double price = 8;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional double price = 8;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>optional double price = 8;</code>
       */
      public Builder setPrice(double value) {
        bitField0_ |= 0x00000080;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double price = 8;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000080);
        price_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object region_ = "";
      /**
       * <code>optional string region = 9;</code>
       */
      public boolean hasRegion() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string region = 9;</code>
       */
      public java.lang.String getRegion() {
        java.lang.Object ref = region_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            region_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string region = 9;</code>
       */
      public com.google.protobuf.ByteString
          getRegionBytes() {
        java.lang.Object ref = region_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          region_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string region = 9;</code>
       */
      public Builder setRegion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        region_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string region = 9;</code>
       */
      public Builder clearRegion() {
        bitField0_ = (bitField0_ & ~0x00000100);
        region_ = getDefaultInstance().getRegion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string region = 9;</code>
       */
      public Builder setRegionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        region_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.google.openbidder.containers.RequestContainer)
    }

    static {
      defaultInstance = new RequestContainer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.google.openbidder.containers.RequestContainer)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_openbidder_containers_RequestContainer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_google_openbidder_containers_RequestContainer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030NativeRtbContainer.proto\022 com.google.o" +
      "penbidder.containers\"\264\001\n\020RequestContaine" +
      "r\022\n\n\002id\030\001 \001(\t\022\017\n\007request\030\002 \001(\014\022\022\n\ncampai" +
      "gnId\030\003 \001(\005\022\022\n\ncreativeId\030\004 \001(\005\022\027\n\017buyerC" +
      "reativeId\030\005 \001(\t\022\024\n\014impressionId\030\006 \001(\005\022\r\n" +
      "\005bidId\030\007 \001(\005\022\r\n\005price\030\010 \001(\001\022\016\n\006region\030\t " +
      "\001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_google_openbidder_containers_RequestContainer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_google_openbidder_containers_RequestContainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_google_openbidder_containers_RequestContainer_descriptor,
        new java.lang.String[] { "Id", "Request", "CampaignId", "CreativeId", "BuyerCreativeId", "ImpressionId", "BidId", "Price", "Region", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
