package com.demo;

import org.apache.avro.Schema;
import org.apache.avro.file.CodecFactory;
import org.apache.avro.file.DataFileReader;
import org.apache.avro.file.DataFileWriter;
import org.apache.avro.file.FileReader;
import org.apache.avro.generic.GenericDatumReader;
import org.apache.avro.generic.GenericRecord;
import org.apache.avro.io.DatumReader;
import org.apache.avro.io.DecoderFactory;
import org.apache.avro.io.Encoder;
import org.apache.avro.io.EncoderFactory;
import org.apache.avro.protobuf.ProtobufData;
import org.apache.avro.protobuf.ProtobufDatumReader;
import org.apache.avro.protobuf.ProtobufDatumWriter;
import org.xerial.snappy.SnappyCodec;

import com.example.tutorial.RealTimeBiddingProtos;
import com.example.tutorial.RealTimeBiddingProtos.BidRequest;
import com.google.openbidder.containers.NativeRtbContainer;
import com.google.protobuf.InvalidProtocolBufferException;


import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
public class ProtoWithAvro {
	public static void main(String[] args) throws IOException {
        System.out.println("******************************************************************************");
        System.out.println("******** DTO classes generated by Protobuff protoc can be used with Avro *****");
        System.out.println("******************************************************************************");
        byte[] data = null;
		NativeRtbContainer.RequestContainer bdreq1=null;
		BidRequest req=null;
		String data1="0A20353732333834464630303032434241323041363838383834464330423841463212BB051210572384FF0002CBA20A688884FC0B8AF2220377A04032BB014D6F7A696C6C612F352E3020284C696E75783B20416E64726F696420342E342E343B20514D6F62696C65205A38204275696C642F4B545538345029204170706C655765624B69742F3533372E333620284B48544D4C2C206C696B65204765636B6F292056657273696F6E2F342E30204368726F6D652F33332E302E302E30204D6F62696C65205361666172692F3533372E333620284D6F62696C653B2061666D612D73646B2D612D76383730333030302E383239383030302E31295A4B68747470733A2F2F706C61792E676F6F676C652E636F6D2F73746F72652F617070732F64657461696C733F69643D636F6D2E526574726F7374796C6547616D65732E53706972697452756E6202656E6A08089F0A150000003F6A0808B50B150000003F7246080110E80210C00210D00210AC0210FA0118D00418E00318980218FA0118FA01220646071E2230164A09108398DAD93D28904E6001700179E7B0C06CC7704E99CD0100FD543B7800A00101AA011B434145534545364B6B395249536E5A57726F704457634743634C6FC801AC02D201033B2857E201B3011A07616E64726F6964321D636F6D2E526574726F7374796C6547616D65732E53706972697452756E38014001480150015881D50358E8D40358E0D40358FC9E046207716D6F62696C656A027A38720608041004180478E8028001D0049001009801D00FA20124572384FF0002CBA20A688884010B8AF2C7AD7387951966B72CE386AF8C43F5729E7F5423C2010A5370697269742052756ECD016BC57B40DA0110A0D03424018F4FACAD8ED3044906AAF3F80101F80180D0F109B8028ADB3DC80201D102E621B656BFACD290980303A103E621B656BFACD290B2032D08011207616E64726F69641A07716D6F62696C6522027A382A06080410041804300038E80240D00448D00F500120A9062A2C504B2D496E7465727374697469616C2D4D6F62696C696E6B2D466F6F7462616C6C2D31343631383136333833300138014100000000389C3C414A0461736961";
		//System.out.println("data1size"+data.toString();
		data = sampleTest.hexStringToByteArray(data1);
		System.out.println("data"+data);
		String hexstring=sampleTest.byteArrayToHexString(data);
		 try {
	    	 bdreq1=NativeRtbContainer.RequestContainer.parseFrom(data);
			System.out.println("bdreq1000000000"+bdreq1.getSerializedSize());
		     req=BidRequest.parseFrom(bdreq1.getRequest().toByteArray());
		    // String jsonView = com.googlecode.protobuf.format.JsonFormat.printToString(req);
			System.out.println("req....."+req.getSerializedSize());
			//System.out.println("jsonView of proto"+jsonView);
			
		} catch (InvalidProtocolBufferException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        // build a protobuff dto
        //RealTimeBiddingProtos.BidRequest.Builder builder = RealTimeBiddingProtos.BidRequest.newBuilder();
        //builder.setTitle("coucou !");
       // RealTimeBiddingProtos.BidRequest req = builder.build();
        

//        // serialize with avro this dto
//        ProtobufDatumWriter<RealTimeBiddingProtos.BidRequest> datumWriter = new ProtobufDatumWriter<RealTimeBiddingProtos.BidRequest>(RealTimeBiddingProtos.BidRequest.class);
//        ByteArrayOutputStream os = new ByteArrayOutputStream();
//        Encoder e = EncoderFactory.get().binaryEncoder(os, null);
//        datumWriter.write(req, e);
//        e.flush();
//
//        // deserialize with avro the former dto
//        ProtobufDatumReader<RealTimeBiddingProtos.BidRequest> datumReader = new ProtobufDatumReader<RealTimeBiddingProtos.BidRequest>(RealTimeBiddingProtos.BidRequest.class);
//        Object o = datumReader.read
//                (null,
//                        DecoderFactory.get().binaryDecoder(new ByteArrayInputStream(os.toByteArray()), null));
//
//        System.out.println("Protobuff DTO deserialized by avro " + o);
//
//        // deserialize with avro, without using the protobuff dto
//        GenericDatumReader<GenericRecord> genericDatumReader = new GenericDatumReader<GenericRecord>(datumReader.getSchema());
//        GenericRecord record = genericDatumReader.read(null, DecoderFactory.get().binaryDecoder(new ByteArrayInputStream(os.toByteArray()), null));
//        System.out.println("Avro Record deserialized data " + record.toString());
//        System.out.println("Avro Record deserialized Schema " + record.getSchema().toString());

		 
		 
		 
        
        ProtobufDatumWriter<RealTimeBiddingProtos.BidRequest> pbWriter = new ProtobufDatumWriter<RealTimeBiddingProtos.BidRequest>(RealTimeBiddingProtos.BidRequest.class);
        DataFileWriter<RealTimeBiddingProtos.BidRequest> dataFileWriter = new DataFileWriter<RealTimeBiddingProtos.BidRequest>(pbWriter);
        Schema schema= ProtobufData.get().getSchema(RealTimeBiddingProtos.BidRequest.class);
        System.out.println("schema"+schema);
        //String path = "/var" +File.separator +"/"+"avro" +File.separator +"/"+  new SimpleDateFormat("yyyyMMddhhmmssSSS'.avro'").format(new Date());
        String path = "D:" +File.separator +"\\"+"logs" +File.separator +"\\"+  new SimpleDateFormat("yyyyMMddhhmmssSSS'.avro'").format(new Date());
        //String fileName = new SimpleDateFormat("yyyyMMddhhmmssSSS'.avro'").format(new Date());
       // String fileName = new SimpleDateFormat("/var/log/open-bidder/yyyyMMddhhmm'.avro'").format(new Date());
        dataFileWriter.setCodec(CodecFactory.snappyCodec()); 
        dataFileWriter.create(schema, new File(path)); 
        dataFileWriter.append(req);
        dataFileWriter.close();


    }
}
